# -*- coding: utf-8 -*-
"""Copy of HW6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tilVO1stN77jve-15vKdJjL8cqEoAygm
"""

import pandas as pd
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

"""##Q4
Please work on your 2nd question below. Please feel free to add new code cells.
"""

#Your code goes here.
world_cup = pd.read_csv('/content/drive/MyDrive/DATA/WorldCupMatches.csv')
world_cup.head()

#your code goes here. Just leaving an example output of an intermediate step for you to check the last two columns
world_cup2 = world_cup.groupby(by=(['Home Team Initials', 'Away Team Initials']))['Home Team Goals'].sum().reset_index()
world_cup3 = world_cup.groupby(by=(['Home Team Initials', 'Away Team Initials']))['Home Team Goals'].count().reset_index()

team_pairs = world_cup.groupby(by=(['Home Team Initials', "Away Team Initials"])).count().reset_index()
team_pairs['weight'] = team_pairs['Year']
team_pairs['HomeTeamGoalTotal'] = world_cup2['Home Team Goals']
team_pairs = team_pairs[['Home Team Initials', 'Away Team Initials', 'weight', 'HomeTeamGoalTotal']]
team_pairs.head()

"""Make sure that you only write four columns ('Home Team Initials', 'Away Team Initials', 'weight', 'HomeGoalTotal') from the data frame, team_pairs, to a csv file"""

team_pairs.to_csv('/content/drive/MyDrive/team_pairs.csv')